spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOSTS}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PWD}
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt:
    tokenHeaderName: "Authorization"
    tokenStart: "Bearer "